var maxheightL0 = maxheight02adjusted();
var maxheightL0px = maxheightL0 + "px";
var maxheightqtnL0 = maxheightL0 * 0.90;
var maxheightqtnL0px = maxheightqtnL0 + "px";
document.getElementById("loaded0").getElementsByTagName("div")[7].style.maxHeight = maxheightL0px;
document.getElementById("loaded0").getElementsByTagName("div")[12].style.maxHeight = maxheightL0px;
document.getElementById("loaded0").getElementsByTagName("div")[13].style.maxHeight = maxheightqtnL0px;
var testheightL0 = document.getElementById("loaded0").getElementsByTagName("div")[13].offsetHeight;
if (testheightL0 > maxheightqtnL0) {document.getElementById("loaded0").getElementsByTagName("div")[13].style.overflowY = "scroll";}
else {document.getElementById("loaded0").getElementsByTagName("div")[13].style.overflowY = "none";};
